version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.3-node
        environment:
          PG_HOST: localhost
          PG_USER: wisp
          RAILS_ENV: test
          RACK_ENV: test
      - image: postgres:9.6
        environment:
          POSTGRES_USER: wisp
          POSTGRES_DB: wisp_test
          POSTGRES_PASSWORD: "password"
    steps:
      - checkout
      - run:
          name: Update Bundler
          command: gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - wisp-bundle-{{ checksum "Gemfile.lock" }}
            - wisp-bundle
      - run:
          name: Bundle Install
          command: bundle check --path ./vendor/bundle || bundle install
      - save_cache:
         key: wisp-bundle-{{ checksum "Gemfile.lock" }}
         paths:
           - ./vendor/bundle
      - run:
          name: Set up DB
          command: bin/rails db:setup
          environment:
            DATABASE_URL: postgres://wisp@localhost:5432/wisp_test
      - run:
          name: Run Specs
          command: bundle exec rspec
          environment:
            DATABASE_URL: postgres://wisp@localhost:5432/wisp_test
