version: 2.1
orbs:
  ruby: circleci/ruby@2.1.3

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.3-node
        environment:
          PG_HOST: localhost
          PG_USER: postgres
          RAILS_ENV: test
          RACK_ENV: test
      - image: cimg/postgres:16.3
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: wisp_test
          POSTGRES_PASSWORD: "password"
    executor: ruby/default
    resource_class: large
    steps:
      - checkout
      - ruby/install-deps:
          key: gems-{{ checksum ".ruby-version" }}
      - run:
          name: Set up database
          command: bundle exec rails db:setup
      - run:
          name: Rspec
          command: bundle exec rspec
