development:
  adapter: postgresql
  encoding: unicode
  database: wisp_development
  pool: 5
  username: wisp
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: wisp_test
  pool: 5
  username: wisp
  password:
