default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('DB_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PWD') { 'password' } %>
  port: <% ENV.fetch('DB_PORT') { 5432 } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: wisp_development

test:
  <<: *default
  database: wisp_test
  url: <%= ENV['DATABASE_URL'] %>

production: &production
  <<: *default
  database: wisp_production
  username: wisp
  password: <%= ENV['WISP_DATABASE_PASSWORD'] %>

staging:
  <<: *production
