default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: wisp_development

test:
  <<: *default
  database: wisp_test
  url: <%= ENV['DATABASE_URL'] %>

production: &production
  <<: *default
  database: wisp_production
  username: wispdb
  password: <%= ENV['WISP_DATABASE_PASSWORD'] %>

staging:
  <<: *production
