development:
  adapter: postgresql
  encoding: unicode
  database: wisp_development
  pool: 5
  username: wisp
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: wisp_test
  pool: 5
  username: wisp
  password:

staging:
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  database: wisp_staging
  pool: 5
  username: wispdb
  password: f8qj&bcI&dadx

production:
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  database: wisp_production
  pool: 5
  username: wispdb
  password: f8qj&bcI&dadx
