development:
  url_options:
    host: 'localhost'
    port: 3000
    protocol: 'http'

test:
  url_options:
    host: 'localhost'
    port: 9887
    protocol: 'http'

staging:
  url_options:
    host: 'dev.wisp.cals.wisc.edu'
    port:
    protocol: 'http'

production:
  url_options:
    host: 'wisp.cals.wisc.edu'
    port:
    protocol: 'http'
