name: Rails Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  rails-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ag_weather_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      RACK_ENV: test
      PG_HOST: localhost
      PG_USER: postgres

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "ruby-3"
          bundler-cache: true

      - name: Set up database
        run: bundle exec rails db:setup

      - name: Run tests
        run: bundle exec rspec
